    language: php

    sudo: true

    cache:
      directories:
        - $HOME/.composer/cache

    services:
      - mysql

    addons:
      apt:
        packages:
         - firefox

    env:
      global:
        - MOODLE_START_BEHAT_SERVERS=NO
        - DB=mysqli
        - MOODLE_CI_VER=1
        - MOODLE_DIR=/home/travis/build/moodle
        - MOODLE_SELENIUM_JAR=/home/travis/build/moodle/selenium34.jar

    matrix:
     include:
      - php: 7.0
        env: MOODLE_BRANCH=MOODLE_34_STABLE MOODLE_CI_VER=2

    before_install:
      - phpenv config-rm xdebug.ini
      - cd ../..
      - composer selfupdate
      - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^${MOODLE_CI_VER}
      - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
      - sleep 10

    install:
      - moodle-plugin-ci install
      - curl -L -s -o ${MOODLE_DIR}/selenium34.jar http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar
      - curl -L -s -o /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
      - sudo tar -C /usr/local/bin/ -xzf /tmp/geckodriver.tar.gz
      - xvfb-run -a --server-args="-screen 0 1024x768x24" java -Dwebdriver.gecko.driver=/usr/local/bin/geckodriver -Dwebdriver.firefox.bin=/usr/bin/firefox -Dwebdriver.firefox.marionette=1 -jar ${MOODLE_SELENIUM_JAR} -log /tmp/selenium.log &
      - php -t ${MOODLE_DIR} -S localhost:8000 > /tmp/php-access.log 2> /tmp/php-error.log &
      - sleep 5s

    script:
      - moodle-plugin-ci phplint
      - moodle-plugin-ci codechecker
      - moodle-plugin-ci phpunit
      - moodle-plugin-ci behat --moodle=${MOODLE_DIR} --auto-rerun=0
